@echo off
@title Starting Alcatraz Registry server...
echo starte server...
java -cp ./dist/AlcatrazOnline.jar:./lib/spread.jar:./lib/alcatraz-lib.jar at.technikum.sam.remote.alcatraz.server.RegistryServer
pause
